# Localization Dictionary
LANG_DICT = {
    "zh": {
        "family": "個人檔案",
        "inventory": "庫存管理",
        "chat": "AI 助手",
        "settings": "設定",
        "lang": "語言選擇",
        "theme": "主題切換",
        "light": "亮色模式",
        "dark": "深色模式",
        "en": "英文",
        "zh": "繁體中文",
        "ai_settings": "AI 設定",
        "api_key": "Gemini API 金鑰",
        "enter_key": "請輸入您的 Gemini API 金鑰",
        "key_saved": "金鑰已儲存",
        "key_missing_msg": "請先在設定中輸入 Gemini API 金鑰以使用功能",
        "new_member": "新增成員",
        "name": "姓名",
        "age": "年齡",
        "gender": "性別",
        "height": "身高",
        "weight": "體重",
        "allergens": "過敏原 (選填)",
        "genetic": "遺傳病史 (選填)",
        "save": "儲存",
        "cancel": "取消",
        "delete_confirm": "確定刪除",
        "delete_msg": "您確定要刪除 '{name}' 嗎？此操作無法復原。",
        "delete_item_msg": "您確定要刪除此項目嗎？",
        "select_height": "選擇身高 (cm)",
        "select_weight": "選擇體重 (kg)",
        "add_item": "新增物品",
        "item_name": "物品名稱",
        "quantity": "數量",
        "expiry_date": "效期 (YYYY-MM-DD)",
        "buy_date": "購買日期 (YYYY-MM-DD)",
        "area": "存放區域 (如：冰箱)",
        "no_members": "尚無家庭成員。\n請點擊 + 新增。",
        "no_items": "尚無庫存物品。\n請點擊 + 新增。",
        "ask_ai": "問問 AI...",
        "male": "男",
        "female": "女",
        "ai_thinking": "AI 正在思考中...",
        "ai_recommendation": "AI 建議",
        "close": "關閉",
        "camera": "照相入庫",
        "ai_recognizing": "AI 正在辨識食物中...",
        "auto_added": "已自動新增：{name}",
        "welcome": "歡迎",
        "username": "使用者名稱",
        "password": "密碼",
        "login": "登入",
        "register": "註冊新帳號",
        "guest": "訪客模式 (離線)",
        "confirm_logout_msg": "您確定要登出嗎？將會回到登入畫面。",
        "logout": "登出"
    },
    "en": {
        "family": "Profile",
        "inventory": "Inventory",
        "chat": "AI Assistant",
        "settings": "Settings",
        "lang": "Language",
        "theme": "Appearance",
        "light": "Light Mode",
        "dark": "Dark Mode",
        "en": "English",
        "zh": "Traditional Chinese",
        "ai_settings": "AI Settings",
        "api_key": "Gemini API Key",
        "enter_key": "Enter your Gemini API Key",
        "key_saved": "Key Saved",
        "key_missing_msg": "Please enter Gemini API Key in Settings to use this feature",
        "new_member": "New Member",
        "name": "Name",
        "age": "Age",
        "gender": "Gender",
        "height": "Height",
        "weight": "Weight",
        "allergens": "Allergens (Optional)",
        "genetic": "Genetic Conditions (Optional)",
        "save": "Save",
        "cancel": "Cancel",
        "delete_confirm": "Confirm Delete",
        "delete_msg": "Are you sure you want to delete '{name}'? This cannot be undone.",
        "delete_item_msg": "Are you sure you want to delete this item?",
        "select_height": "Select Height (cm)",
        "select_weight": "Select Weight (kg)",
        "add_item": "Add Item",
        "item_name": "Item Name",
        "quantity": "Quantity",
        "expiry_date": "Expiry (YYYY-MM-DD)",
        "buy_date": "Buy Date (YYYY-MM-DD)",
        "area": "Area (e.g. Fridge)",
        "no_members": "No family members found.\nTap + to add one.",
        "no_items": "No items in inventory.\nTap + to add one.",
        "ask_ai": "Ask AI...",
        "male": "Male",
        "female": "Female",
        "ai_thinking": "AI is thinking...",
        "ai_recommendation": "AI Suggestion",
        "close": "Close",
        "camera": "Camera Entry",
        "ai_recognizing": "AI is identifying food...",
        "auto_added": "Auto-added: {name}",
        "welcome": "Welcome",
        "username": "Username",
        "password": "Password",
        "login": "Login",
        "register": "Register New Account",
        "guest": "Continue as Guest (Offline)",
        "confirm_logout_msg": "Are you sure you want to logout? You will return to the login screen.",
        "logout": "Logout"
    }
}
