# Localization Dictionary
LANG_DICT = {
    "zh": {
        "family": "個人檔案",
        "inventory": "庫存管理",
        "calories": "卡路里",
        "chat": "AI 助手",
        "settings": "設定",
        "lang": "語言選擇",
        "theme": "主題切換",
        "light": "亮色模式",
        "dark": "深色模式",
        "en": "英文",
        "zh": "繁體中文",
        "ai_settings": "AI 設定",
        "api_key": "Gemini API 金鑰",
        "enter_key": "請輸入您的 Gemini API 金鑰",
        "key_saved": "金鑰已儲存",
        "key_missing_msg": "請先在設定中輸入 Gemini API 金鑰以使用功能",
        "new_member": "新增成員",
        "add_member": "新增成員",
        "name": "姓名",
        "age": "年齡",
        "gender": "性別",
        "height": "身高",
        "weight": "體重",
        "allergens": "過敏原 (選填)",
        "genetic": "遺傳病史 (選填)",
        "save": "儲存",
        "cancel": "取消",
        "delete_confirm": "確定刪除",
        "delete_msg": "您確定要刪除 '{name}' 嗎？此操作無法復原。",
        "delete_item_msg": "您確定要刪除此項目嗎？",
        "select_height": "選擇身高 (cm)",
        "select_weight": "選擇體重 (kg)",
        "add_item": "新增物品",
        "item_name": "物品名稱",
        "quantity": "數量",
        "expiry_date": "效期 (YYYY-MM-DD)",
        "buy_date": "購買日期 (YYYY-MM-DD)",
        "area": "存放區域 (如：冰箱)",
        "no_members": "尚無家庭成員。\n請點擊 + 新增。",
        "no_items": "尚無庫存物品\n請點擊右上角按鈕新增",
        "ask_ai": "問問 AI...",
        "male": "男",
        "female": "女",
        "ai_thinking": "AI 正在思考中...",
        "ai_recommendation": "AI 建議",
        "close": "關閉",
        "camera": "照相入庫",
        "ai_recognizing": "AI 正在辨識食物中...",
        "auto_added": "已自動新增：{name}",
        "welcome": "歡迎",
        "username": "使用者名稱",
        "password": "密碼",
        "login": "登入",
        "register": "註冊新帳號",
        "guest": "訪客模式 (離線)",
        "confirm_logout_msg": "您確定要登出嗎？將會回到登入畫面。",
        "confirm_logout_msg": "您確定要登出嗎？將會回到登入畫面。",
        "logout": "登出",
        "remember_me": "記住我",
        "cat_frozen": "冷凍",
        "cat_fridge": "冷藏",
        "cat_dry": "乾貨",
        "cat_seasoning": "調味料",
        "cat_general": "一般",
        "select_area": "選擇區域",
        "ok": "確定",
        "error_title": "錯誤",
        "success_title": "成功",
        "login_error_empty": "請輸入使用者名稱和密碼",
        "login_error_failed": "登入失敗，請檢查帳號密碼。",
        "register_success": "帳號建立成功！正在登入...",
        "register_failed": "註冊失敗，使用者名稱可能已被使用。",
        "select_photo": "選擇食物照片",
        "recog_failed": "辨識失敗，請重試。",
        "general": "一般",
        "unknown": "未知",
        "cal_today": "今日熱量 (kcal)",
        "cal_weekly": "本週趨勢",
        "cal_history": "今日紀錄",
        "cal_add_title": "熱量計算機",
        "cal_calculate": "AI 計算",
        "cal_input_hint": "輸入食物",
        "cal_breakfast": "早餐",
        "cal_lunch": "午餐",
        "cal_dinner": "晚餐",
        "cal_snack": "消夜",
        "cal_no_record": "今日尚無紀錄",
        "cal_estimate": "預估熱量",
        "cal_saved": "已儲存",
        "cal_saved": "已儲存",
        "sugg_recipe": "推薦食譜",
        "sugg_exercise": "運動飲食",
        "sugg_shopping": "採購清單",
        "msg_recipe": "能幫我推薦一些基於目前庫存的健康食譜嗎？（避開過敏原）",
        "msg_exercise": "我今天要運動，適合吃什麼來補充能量？",
        "msg_shopping": "我要去採購，根據家庭需求我買什麼合適？",
        "health_warning": "【健康警示】",
        "rec_recipes": "今日推薦食譜",
        "shopping_list": "建議採買清單",
        "calories_estimate": "預估熱量",
        "rec_recipe_hint": "點擊右上方圖示\n為您生成今日專屬食譜",
        "gen_recipe_msg": "正在根據庫存與家庭資料生成食譜...\n約需 30 秒，請稍候",
        "recipe_title": "美味食譜",
        "equipment": "廚房設備",
        "oven": "烤箱",
        "microwave": "微波爐",
        "air_fryer": "氣炸鍋",
        "pan": "平底鍋",
        "pot": "湯鍋",
        "rice_cooker": "電鍋",
        "blender": "果汁機",
        "add_custom_hint": "輸入自定義器材...",
        "save_success": "儲存成功",
        "cal_camera": "卡路里照相",
        "confirm_save_cal": "辨識結果: {food}\n預估熱量: {cal} kcal\n是否儲存此次紀錄?",
        "cal_recognizing": "AI 正在分析食物卡路里...",
        "save": "儲存",
        "manual_entry": "手動輸入",
        "camera_entry": "AI 拍照辨識",
        "u_type": "單位類型",
        "u_unit": "單位",
        "u_weight": "重量",
        "u_volume": "容量",
        "u_qty": "件數",
        "unit_g": "克 (g)",
        "unit_kg": "公斤 (kg)",
        "unit_ml": "毫升 (ml)",
        "unit_l": "公升 (l)",
        "unit_pc": "個 (unit)",
        "short_buy": "購",
        "short_exp": "期",
        "short_unit_g": "g",
        "short_unit_kg": "kg",
        "short_unit_ml": "ml",
        "short_unit_l": "l",
        "short_unit_pc": "個",
    },
    "en": {
        "family": "Profile",
        "inventory": "Inventory",
        "calories": "Calories",
        "chat": "AI Assistant",
        "settings": "Settings",
        "lang": "Language",
        "theme": "Appearance",
        "light": "Light Mode",
        "dark": "Dark Mode",
        "en": "English",
        "zh": "Traditional Chinese",
        "ai_settings": "AI Settings",
        "api_key": "Gemini API Key",
        "enter_key": "Enter your Gemini API Key",
        "key_saved": "Key Saved",
        "key_missing_msg": "Please enter Gemini API Key in Settings to use this feature",
        "new_member": "New Member",
        "add_member": "Add Member",
        "name": "Name",
        "age": "Age",
        "gender": "Gender",
        "height": "Height",
        "weight": "Weight",
        "allergens": "Allergens (Optional)",
        "genetic": "Genetic Conditions (Optional)",
        "save": "Save",
        "cancel": "Cancel",
        "delete_confirm": "Confirm Delete",
        "delete_msg": "Are you sure you want to delete '{name}'? This cannot be undone.",
        "delete_item_msg": "Are you sure you want to delete this item?",
        "select_height": "Select Height (cm)",
        "select_weight": "Select Weight (kg)",
        "add_item": "Add Item",
        "item_name": "Item Name",
        "quantity": "Quantity",
        "expiry_date": "Expiry (YYYY-MM-DD)",
        "buy_date": "Buy Date (YYYY-MM-DD)",
        "area": "Area (e.g. Fridge)",
        "no_members": "No family members found.\nTap + to add one.",
        "no_items": "No items.\nTap top-right to add.",
        "ask_ai": "Ask AI...",
        "male": "Male",
        "female": "Female",
        "ai_thinking": "AI is thinking...",
        "ai_recommendation": "AI Suggestion",
        "close": "Close",
        "camera": "Camera Entry",
        "ai_recognizing": "AI is identifying food...",
        "auto_added": "Auto-added: {name}",
        "welcome": "Welcome",
        "username": "Username",
        "password": "Password",
        "login": "Login",
        "register": "Register New Account",
        "guest": "Continue as Guest (Offline)",
        "confirm_logout_msg": "Are you sure you want to logout? You will return to the login screen.",
        "confirm_logout_msg": "Are you sure you want to logout? You will return to the login screen.",
        "logout": "Logout",
        "remember_me": "Remember Me",
        "cat_frozen": "Frozen",
        "cat_fridge": "Refrigerated",
        "cat_dry": "Dry Goods",
        "cat_seasoning": "Seasoning",
        "cat_general": "General",
        "select_area": "Select Area",
        "ok": "OK",
        "error_title": "Error",
        "success_title": "Success",
        "login_error_empty": "Please enter username and password",
        "login_error_failed": "Login failed. Check credentials.",
        "register_success": "Account created! Logging in...",
        "register_failed": "Registration failed. Username may be taken.",
        "select_photo": "Select Food Photo",
        "recog_failed": "Recognition failed. Please try again.",
        "general": "General",
        "unknown": "Unknown",
        "cal_today": "Today's Calories (kcal)",
        "cal_weekly": "Weekly Trend",
        "cal_history": "Today's History",
        "cal_add_title": "Calorie Calculator",
        "cal_calculate": "AI Calculate",
        "cal_input_hint": "Enter food name",
        "cal_breakfast": "Breakfast",
        "cal_lunch": "Lunch",
        "cal_dinner": "Dinner",
        "cal_snack": "Snack",
        "cal_no_record": "No records today",
        "cal_estimate": "Estimated Calories",
        "cal_saved": "Saved",
        "cal_saved": "Saved",
        "sugg_recipe": "Recipes",
        "sugg_exercise": "Exercise",
        "sugg_shopping": "Shopping",
        "msg_recipe": "Can you suggest some healthy recipes based on current inventory? (Avoid allergens)",
        "msg_exercise": "I'm going to exercise today, what should I eat for energy?",
        "msg_shopping": "I'm going shopping, what should I buy for my family?",
        "health_warning": "[Health Warning]",
        "rec_recipes": "Daily Recipes",
        "shopping_list": "Shopping List",
        "calories_estimate": "Est. Calories",
        "rec_recipe_hint": "Click the top-right icon\nto generate today's recipes",
        "gen_recipe_msg": "Generating recipes based on inventory and family data...\nTakes approx. 30 seconds, please wait",
        "recipe_title": "Tasty Recipe",
        "equipment": "Kitchen Appliances",
        "oven": "Oven",
        "microwave": "Microwave",
        "air_fryer": "Air Fryer",
        "pan": "Frying Pan",
        "pot": "Soup Pot",
        "rice_cooker": "Rice Cooker",
        "blender": "Blender",
        "add_custom_hint": "Enter custom equipment...",
        "save_success": "Saved Successfully",
        "cal_camera": "Calorie Camera",
        "confirm_save_cal": "Result: {food}\nEst. Calories: {cal} kcal\nSave this record?",
        "cal_recognizing": "AI is analyzing calories...",
        "save": "Save",
        "manual_entry": "Manual Entry",
        "camera_entry": "AI Recognition",
        "u_type": "Unit Type",
        "u_unit": "Unit",
        "u_weight": "Weight",
        "u_volume": "Volume",
        "u_qty": "Quantity",
        "unit_g": "g",
        "unit_kg": "kg",
        "unit_ml": "ml",
        "unit_l": "l",
        "unit_pc": "unit",
        "short_buy": "Buy",
        "short_exp": "Exp",
        "short_unit_g": "g",
        "short_unit_kg": "kg",
        "short_unit_ml": "ml",
        "short_unit_l": "l",
        "short_unit_pc": "unit",
    }
}
